name: Jenkins Test Instance Pipeline Trigger

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  trigger-jenkins-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Get Jenkins Crumb
        id: get-crumb
        run: |
          CRUMB=$(curl -u palrag:${{ secrets.CSRF_GITHUB_JENKINS_TOKEN }} http://54.89.32.115:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb))
          echo "::set-output name=crumb::$CRUMB"

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST -H "${{ steps.get-crumb.outputs.crumb }}" "http://54.89.32.115:8080/job/PalragDeployPipeline/build"
