name: Jenkins Test Instance Pipeline Trigger

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  trigger-jenkins-pipeline:
    runs-on: ubuntu-20.04

    steps:
      - name: Trigger Jenkins Pipeline
        run: |

          echo "Jenkins build triggered"
