name: Jenkins Pipeline Trigger For Test Machine

on:
  push:
    branches:
      - test  

jobs:
  trigger-jenkins-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Pipeline
        env:
          JENKINS_WEBHOOK_SECRET: ${{ secrets.JENKINS_WEBHOOK_SECRET }}
        run: |
          
